In [1]:
from src import PDBio
import pandas as pd
import numpy as np
from src.ResRepr import ResRepr
import itertools
from scipy.spatial import KDTree
from src.DataModel import dataModel, DataModel
from artemis import ARTEMIS, mutuallyClosest


In [2]:
resRepr = ResRepr('artemis')

In [3]:
r = 'test/1/3w3sB.pdb'
rname = '3w3sB'
rformat = '.pdb'
rres = '#1'
rresneg = False
rseed = '#1'
rsaveres = '#'

q = 'test/1/2nreF.pdb'
qname = '2nreF'
qformat = '.pdb'
qres = '#1'
qresneg = False
qseed = '#1'
qsaveres = '#'

In [4]:
r = dataModel(
    rname, rformat, r,
    rres, rseed, rsaveres,
    rresneg,
    resRepr
)

q = dataModel(
    qname, qformat, q,
    qres, qseed, qsaveres,
    qresneg,
    resRepr
)

In [5]:
artemis = ARTEMIS(r, q)

In [6]:
artemis.run()

ValueError: max() arg is an empty sequence

In [ ]:
artemis.ans

AttributeError: 'ARTEMIS' object has no attribute 'ans'

In [6]:
seed = list(artemis.get_seed())

In [7]:
h = mutuallyClosest(artemis.hit(*seed[2]))
h

array([[95, 96, 94,  0, 91, 86, 88],
       [53, 54, 52,  2, 48, 16, 13]])

In [8]:
artemis.align(h[0], h[1])

(((array([[ 0.02021676,  0.48477154, -0.87440713],
          [ 0.45083518, -0.78504117, -0.42480348],
          [-0.89237824, -0.38562535, -0.23442305]]),
   array([-25.43550809, -35.55373349,  60.76090569])),
  (0.10485091148143302, 0.11714729087516575),
  4.334873267186187,
  (array([ 0,  1,  2,  3,  4,  5,  6, 13, 14, 15, 16, 85, 86, 87, 90, 91, 92,
          93, 94, 95]),
   array([ 0,  1,  2,  3,  4,  5,  6, 21, 22, 23, 24, 53, 54, 55,  7,  8,  9,
          10, 46, 12]))),
 ((array([[ 0.09291371,  0.55887009, -0.82403353],
          [ 0.58347216, -0.70118184, -0.40976123],
          [-0.80680064, -0.44272819, -0.39123455]]),
   array([-23.84386445, -31.13556642,  63.29509046])),
  (0.06993301824074201, 0.06767119921126881),
  5.083527000851853,
  ('gggagag--------------guuggccggc--------uggugccgccccgggacuucaaaucccgugggaggucccgcaagggagcuccggaggguucgauuc-------------------ccucccucucccgcc',
   'aggugguggaauugguagaca------cgcuaccgguag---------------------------------------------------

In [13]:
mask = np.array([r.c[i] is not None for i in h[0]])\
   | np.array([q.c[i] is not None for i in h[1]]) 

In [18]:
np.where(mask)[0]

array([0, 1, 2, 3, 4, 5, 6])

In [19]:
r.c[np.where(mask)[0]]

array([array([[-65.754 , -12.544 ,  73.7145],
              [-69.4995, -14.3235,  73.0395],
              [-68.222 , -15.727 ,  71.1   ]]),
       array([[-69.2175, -15.3375,  77.058 ],
              [-70.368 , -19.368 ,  76.2985],
              [-68.738 , -19.659 ,  74.165 ]]),
       array([[-69.037 , -20.7175,  79.8545],
              [-67.889 , -24.378 ,  78.063 ],
              [-66.342 , -23.293 ,  76.131 ]]),
       array([[-66.1755, -25.598 ,  81.5285],
              [-63.4095, -27.999 ,  79.4265],
              [-62.755 , -25.864 ,  77.994 ]]),
       array([[-60.9265, -29.0385,  82.391 ],
              [-57.6395, -29.12  ,  79.777 ],
              [-57.97  , -26.584 ,  78.841 ]]),
       array([[-54.875 , -29.8805,  82.5   ],
              [-51.967 , -27.4465,  80.9005],
              [-53.297 , -25.126 ,  80.567 ]]),
       array([[-50.0265, -27.622 ,  84.2775],
              [-48.682 , -23.61  ,  83.2605],
              [-51.15  , -22.4   ,  83.273 ]])], dtype=object)